# VERKOOP GBS
# 8001,8002,8003,8004,8005,8006,8007,8009,8014,8015,8022,8029,8031,8033,8034,8035,8036,8037,8038,8039,8042

# INKOOP GBS
# 8023,8024,8032,8040,8041,8043,8044

SELECT
  FRordORDER.ORDORNRINT as order_id,
  FRordORDER.ORDORNR as order_nr,
  FRordORDER.ORDORDATUM as order_date,
  FRordORDER.ORDOROMS as order_description,
  FRordORDER.ORDORREFERENTIE as order_reference,
  '0' as order_type,

  FRordORDERREGEL.ORDRRNRINT as new_orderrule_id,
  FRordORDERREGEL.ORDRR_REF_OUD as old_orderrule_id,
  (CASE WHEN FRordORDERREGEL.ORDRR_REF_OUD = "" THEN FRordORDERREGEL.ORDRRNRINT ELSE FRordORDERREGEL.ORDRR_REF_OUD END) as orderrule_id,
  TO_BASE64(CONCAT(FRordORDER.ORDORNRINT,'_',(CASE WHEN FRordORDERREGEL.ORDRR_REF_OUD = "" THEN FRordORDERREGEL.ORDRRNRINT ELSE FRordORDERREGEL.ORDRR_REF_OUD END))) as object_id,
  #(CASE WHEN FRordORDERREGEL.ORDRR_REF_OUD = "" THEN FRordORDERREGEL.ORDRRNRINT ELSE CONCAT('1_', FRordORDERREGEL.ORDRR_REF_OUD) END) as orderrule_id,
  #FRordORDERREGEL.ORDRRAANTAL as orderrule_quantity,
  (CASE WHEN FRordORDERREGEL.ORDRR_INAFROEP > 0 THEN ORDRR_INAFROEP ELSE ORDRRAANTAL END) as orderrule_quantity,
  FRordORDERREGEL.ORDRROMS as orderrule_description,

  FRbkhARTIKEL.BKHARNRINT as product_id,
  FRbkhARTIKEL.BKHARCODE as product_code,
  FRbkhARTIKEL.BKHAROMS as product_description,

  FRbkhGROOTBOEK.BKHGBNRINT as ledger_id,
  FRbkhGROOTBOEK.BKHGBNR as ledger_code,
  FRbkhGROOTBOEK.BKHGBOMS as ledger_name,

  FRbkhADRES.BKHADNRINT as adres_id,
  FRbkhADRES.BKHADCODE as adres_code,
  FRbkhADRES.BKHADNAAM as adres_name,
  CONCAT(FRbkhADRES.BKHADADRES_W, ' ', FRbkhADRES.BKHADADRES_HNR, FRbkhADRES.BKHADADRES_HNR_TOE) as adres_address,
  FRbkhADRES.BKHADPOSTCODE as adres_postalcode,
  FRbkhADRES.BKHADPLAATS as adres_town,
  FRbkhLANDADRES.BKHLACODE as adres_countrycode,
  FRbkhLANDADRES.BKHLAOMS as adres_countryname,
  FRbkhADRES.BKHADWEBSITE as adres_website,

  FRordORDER.ORDOR_BKHAAFNRINT as afleveradres_id,
  FRbkhADRES.BKHADCODE as afleveradres_code,
  FRbkhADRES_AFLEVER.BKHAAFNAAM as afleveradres_name,
  CONCAT(FRbkhADRES_AFLEVER.BKHAAFSTRAAT, ' ', FRbkhADRES_AFLEVER.BKHAAFHUISNR, FRbkhADRES_AFLEVER.BKHAAFHUISNRTOE) as afleveradres_address,
  FRbkhADRES_AFLEVER.BKHAAFPOSTCODE as afleveradres_postalcode,
  FRbkhADRES_AFLEVER.BKHAAFPLAATS as afleveradres_town,
  FRbkhLANDAFLEVER.BKHLACODE as afleveradres_countrycode,
  FRbkhLANDAFLEVER.BKHLAOMS as afleveradres_countryname,

  FRordMEDEWERKER.ORDMWCODE as employee_code,
  FRordMEDEWERKER.ORDMWNAAM as employee_name
FROM
  FRordORDERREGEL

LEFT JOIN
  FRordORDER ON ORDRR_ORDORNRINT = ORDORNRINT

LEFT JOIN
  FRbkhARTIKEL ON ORDRR_BKHARNRINT = BKHARNRINT

LEFT JOIN
  FRbkhADRES ON ORDOR_BKHADNRINT = BKHADNRINT

LEFT JOIN
  FRbkhLAND FRbkhLANDADRES ON BKHAD_BKHLANRINT = FRbkhLANDADRES.BKHLANRINT

LEFT JOIN
  FRbkhADRES_AFLEVER ON ORDOR_BKHAAFNRINT = BKHAAFNRINT

LEFT JOIN
  FRbkhLAND FRbkhLANDAFLEVER ON BKHAAF_BKHLANRINT = FRbkhLANDAFLEVER.BKHLANRINT

LEFT JOIN
  FRbkhGROOTBOEK ON BKHAR_BKHGBNRINT_VF = BKHGBNRINT

LEFT JOIN
  FRordMEDEWERKER ON ORDOR_ORDMWNRINT = ORDMWNRINT

WHERE
  FRordORDERREGEL.ORDRR_PLANNING = 1
AND
  FRordORDER.ORDORDATUM >= CURDATE() - INTERVAL 13 MONTH


UNION ALL


SELECT
  FRinkBESTEL.INKBENRINT as order_id,
  FRinkBESTEL.INKBENR as order_nr,
  FRinkBESTEL.INKBEDTM as order_date,
  FRinkBESTEL.INKBEOMS as order_description,
  "" as order_reference,
  '1' as order_type,

  FRinkBESTELREGEL.INKBLNRINT as new_orderrule_id,
  FRinkBESTELREGEL.INKBL_REF_OUD as old_orderrule_id,
  (CASE WHEN FRinkBESTELREGEL.INKBL_REF_OUD = "" THEN FRinkBESTELREGEL.INKBLNRINT ELSE FRinkBESTELREGEL.INKBL_REF_OUD END) as orderrule_id,
  TO_BASE64(CONCAT(FRinkBESTEL.INKBENRINT,'_',(CASE WHEN FRinkBESTELREGEL.INKBL_REF_OUD = "" THEN FRinkBESTELREGEL.INKBLNRINT ELSE FRinkBESTELREGEL.INKBL_REF_OUD END))) as object_id,
  #(CASE WHEN FRinkBESTELREGEL.INKBL_REF_OUD = "" THEN FRinkBESTELREGEL.INKBLNRINT ELSE CONCAT('1_', FRinkBESTELREGEL.INKBL_REF_OUD) END) as orderrule_id,
  FRinkBESTELREGEL.INKBLAANTAL_BE as orderrule_quantity,
  FRinkBESTELREGEL.INKBLOMS as orderrule_description,

  FRbkhARTIKEL.BKHARNRINT as product_id,
  FRbkhARTIKEL.BKHARCODE as product_code,
  FRbkhARTIKEL.BKHAROMS as product_description,

  FRbkhGROOTBOEK.BKHGBNRINT as ledger_id,
  FRbkhGROOTBOEK.BKHGBNR as ledger_code,
  FRbkhGROOTBOEK.BKHGBOMS as ledger_name,

  FRbkhADRES.BKHADNRINT as adres_id,
  FRbkhADRES.BKHADCODE as adres_code,
  FRbkhADRES.BKHADNAAM as adres_name,
  CONCAT(FRbkhADRES.BKHADADRES_W, ' ', FRbkhADRES.BKHADADRES_HNR, FRbkhADRES.BKHADADRES_HNR_TOE) as adres_address,
  FRbkhADRES.BKHADPOSTCODE as adres_postalcode,
  FRbkhADRES.BKHADPLAATS as adres_town,
  FRbkhLANDADRES.BKHLACODE as adres_countrycode,
  FRbkhLANDADRES.BKHLAOMS as adres_countryname,
  FRbkhADRES.BKHADWEBSITE as adres_website,

  FRinkBESTEL.INKBE_BKHAAFNRINT as afleveradres_id,
  FRbkhADRES.BKHADCODE as afleveradres_code,
  FRbkhADRES_AFLEVER.BKHAAFNAAM as afleveradres_name,
  CONCAT(FRbkhADRES_AFLEVER.BKHAAFSTRAAT, ' ', FRbkhADRES_AFLEVER.BKHAAFHUISNR, FRbkhADRES_AFLEVER.BKHAAFHUISNRTOE) as afleveradres_address,
  FRbkhADRES_AFLEVER.BKHAAFPOSTCODE as afleveradres_postalcode,
  FRbkhADRES_AFLEVER.BKHAAFPLAATS as afleveradres_town,
  FRbkhLANDAFLEVER.BKHLACODE as afleveradres_countrycode,
  FRbkhLANDAFLEVER.BKHLAOMS as afleveradres_countryname,

  ORDMWCODE as employee_code,
  ORDMWNAAM as employee_name

FROM
  FRinkBESTELREGEL

LEFT JOIN
  FRinkBESTEL ON INKBL_INKBENRINT = INKBENRINT

LEFT JOIN
  FRbkhARTIKEL ON INKBL_BKHARNRINT = BKHARNRINT

LEFT JOIN
  FRbkhADRES ON INKBE_BKHADNRINT = BKHADNRINT

LEFT JOIN
  FRbkhLAND FRbkhLANDADRES ON BKHAD_BKHLANRINT = FRbkhLANDADRES.BKHLANRINT

LEFT JOIN
  FRbkhADRES_AFLEVER ON INKBE_BKHAAFNRINT = BKHAAFNRINT

LEFT JOIN
  FRbkhLAND FRbkhLANDAFLEVER ON BKHAAF_BKHLANRINT = FRbkhLANDAFLEVER.BKHLANRINT

LEFT JOIN
  FRbkhGROOTBOEK ON BKHAR_BKHGBNRINT_VF = BKHGBNRINT

LEFT JOIN
  FRordMEDEWERKER ON INKBE_ORDMWNRINT = ORDMWNRINT

WHERE
  FRinkBESTELREGEL.INKBL_PLANNING = 1

AND
  FRinkBESTEL.ORDORDATUM >= INKBEDTM() - INTERVAL 13 MONTH
