version: "3.3"
services:
  cli:
#    image: php:7.3-cli
    build:
      context: ./
      dockerfile: ./cli.docker
#    volumes:
#      - ./log:/var/log
#    deploy:
#      restart_policy:
#        condition: any
#        # run every 2 minutes
#        delay: 2m