PenD\Docker\Application\Model\Printjobuniqueattributes:
    type: entity
    table: PrintJobUniqueAttributes
    indexes:
        IX_PrintJobUniqueAttributes:
            columns:
                - Key
                - JobType
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Key
        jobtype:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: JobType
        usedon:
            type: datetime
            nullable: false
            column: UsedOn
    lifecycleCallbacks: {  }
