PenD\Docker\Application\Model\Prereceiptpurchaseorders:
    type: entity
    table: PreReceiptPurchaseOrders
    indexes:
        IDX_6DFBCB557FA0968C:
            columns:
                - PreReceipt_fk
    id:
        prereceiptpurchaseorderPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PreReceiptPurchaseOrder_pk
            generator:
                strategy: IDENTITY
    fields:
        purchaseorderid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PurchaseOrderId
        ordernumber:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: OrderNumber
        dateordered:
            type: datetime
            nullable: true
            column: DateOrdered
        datefirstexpected:
            type: datetime
            nullable: true
            column: DateFirstExpected
        description:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: Description
        projectcode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ProjectCode
        projectname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: ProjectName
        businessunit:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: BusinessUnit
        vendornumber:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VendorNumber
        vendorname:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: VendorName
        vendoraddressline1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VendorAddressLine1
        vendoraddressline2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VendorAddressLine2
        vendoraddressline3:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VendorAddressLine3
        vendorzipcode:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VendorZipCode
        vendorcity:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VendorCity
        vendorstate:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VendorState
        vendorcountrycode:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: VendorCountryCode
        vendorcountryname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: VendorCountryName
        vendorcontact:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: VendorContact
        vendorcontactemail:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: VendorContactEmail
        vendorphonenumber:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VendorPhoneNumber
        deliverymethod:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: DeliveryMethod
        selectioncode:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: SelectionCode
        selectioncodedescription:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: SelectionCodeDescription
    manyToOne:
        prereceiptFk:
            targetEntity: PenD\Docker\Application\Model\Prereceipts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PreReceipt_fk:
                    referencedColumnName: PreReceipt_pk
            orphanRemoval: false
    lifecycleCallbacks: {  }
