PenD\Docker\Application\Model\Tags:
    type: entity
    table: Tags
    id:
        tagPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Tag_pk
            generator:
                strategy: IDENTITY
    fields:
        color:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Color
        description:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Description
        target:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Target
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
