PenD\Docker\Application\Model\Shipmentdocuments:
    type: entity
    table: ShipmentDocuments
    id:
        shipmentdocumentPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ShipmentDocument_pk
            generator:
                strategy: IDENTITY
    fields:
        shipmentFk:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Shipment_fk
        documenttype:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: DocumentType
        documentdata:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
            column: DocumentData
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
