PenD\Docker\Application\Model\Warehousetransfers:
    type: entity
    table: WarehouseTransfers
    id:
        warehousetransfersPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: WarehouseTransfers_pk
            generator:
                strategy: IDENTITY
    fields:
        batchFk:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Batch_fk
        groupguid:
            type: guid
            nullable: false
            length: null
            options:
                fixed: false
                default: newid()
            column: GroupGuid
        description:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Description
        processdate:
            type: datetime
            nullable: true
            column: ProcessDate
        warehousefrom:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: WarehouseFrom
        warehouselocationfrom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: WarehouseLocationFrom
        warehouseto:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: WarehouseTo
        warehouselocationto:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: WarehouseLocationTo
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
