PenD\Docker\Application\Model\Labels:
    type: entity
    table: Labels
    uniqueConstraints:
        IX_Unique_Name:
            columns:
                - Name
    id:
        labelPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Label_PK
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Name
        description:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: Description
        image:
            type: blob
            nullable: true
            length: null
            options:
                fixed: false
            column: Image
        printercode:
            type: text
            nullable: false
            length: -1
            options:
                fixed: false
            column: PrinterCode
        fieldregex:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
            column: FieldRegEx
        datasettypename:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
                comment: 'Name of the dataset to map to'
            column: DataSetTypeName
        mapping:
            type: blob
            nullable: true
            length: null
            options:
                fixed: false
            column: Mapping
        sys:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: Sys
        onelabelperprintaction:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: OneLabelPerPrintAction
        isactive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: IsActive
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
