PenD\Docker\Application\Model\Licenseplateitems:
    type: entity
    table: LicensePlateItems
    indexes:
        IDX_8115015724A31E3B:
            columns:
                - LicensePlate_fk
    uniqueConstraints:
        IX_LicensePlateItems:
            columns:
                - LicensePlate_fk
                - ItemCode
                - ItemId
    id:
        licenseplateitemPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: LicensePlateItem_pk
            generator:
                strategy: IDENTITY
    fields:
        itemcode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ItemCode
        itemdescription:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: ItemDescription
        isserialitem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsSerialItem
        isbatchitem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsBatchItem
        itemid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ItemId
        quantity:
            type: decimal
            nullable: true
            precision: 19
            scale: 4
            column: Quantity
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    manyToOne:
        licenseplateFk:
            targetEntity: PenD\Docker\Application\Model\Licenseplates
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                LicensePlate_fk:
                    referencedColumnName: LicensePlate_pk
            orphanRemoval: false
    lifecycleCallbacks: {  }
