PenD\Docker\Application\Model\Warehouses:
    type: entity
    table: Warehouses
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        warehousecode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: WarehouseCode
        defaultinboundlocation:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: DefaultInboundLocation
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
