PenD\Docker\Application\Model\Prereceiptlines:
    type: entity
    table: PreReceiptLines
    indexes:
        IDX_67ED0CE27FA0968C:
            columns:
                - PreReceipt_fk
    id:
        prereceiptlinesPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PreReceiptLines_pk
            generator:
                strategy: IDENTITY
    fields:
        itemcode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: ItemCode
        itemdescription:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: ItemDescription
        defaultvendoritemcode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: DefaultVendorItemCode
        currentvendoritemcode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: CurrentVendorItemCode
        purchaseordernumber:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: PurchaseOrderNumber
        purchaseorderid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PurchaseOrderId
        purchaseorderlineid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PurchaseOrderLineId
        purchaseorderlinenumber:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PurchaseOrderLineNumber
        suppliername:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: SupplierName
        suppliercode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: SupplierCode
        isbatchnumberitem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsBatchNumberItem
        isserialnumberitem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsSerialNumberItem
        quantityordered:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            column: QuantityOrdered
        quantitysupplierpackageslip:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            column: QuantitySupplierPackageSlip
        quantity:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            column: Quantity
        unitcode:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: UnitCode
        warehousecode:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: WarehouseCode
        salesunitcode:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: SalesUnitCode
        salesunitfactor:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            column: SalesUnitFactor
        lineinstruction:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LineInstruction
        linecurrencycode:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: LineCurrencyCode
        itempurchaseprice:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            options:
                default: '0'
            column: ItemPurchasePrice
        customfields:
            type: blob
            nullable: true
            length: null
            options:
                fixed: false
            column: CustomFields
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    manyToOne:
        prereceiptFk:
            targetEntity: PenD\Docker\Application\Model\Prereceipts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PreReceipt_fk:
                    referencedColumnName: PreReceipt_pk
            orphanRemoval: false
    lifecycleCallbacks: {  }
