PenD\Docker\Application\Model\Batchactivity:
    type: entity
    table: BatchActivity
    id:
        batchactivityPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: BatchActivity_pk
            generator:
                strategy: IDENTITY
    fields:
        batchesFk:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Batches_fk
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: UserName
        devicename:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: DeviceName
        activity:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Activity
        time:
            type: datetime
            nullable: false
            column: Time
        notes:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: Notes
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
