PenD\Docker\Application\Model\Devices:
    type: entity
    table: Devices
    id:
        devicePk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Device_pk
            generator:
                strategy: IDENTITY
    fields:
        macaddress:
            type: string
            nullable: false
            length: 17
            options:
                fixed: false
            column: MacAddress
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Name
        createdon:
            type: datetime
            nullable: false
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
