PenD\Docker\Application\Model\Rmaorders:
    type: entity
    table: RmaOrders
    id:
        rmaordersPk:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: RmaOrders_pk
            generator:
                strategy: IDENTITY
    fields:
        groupguid:
            type: guid
            nullable: true
            length: null
            options:
                fixed: false
            column: GroupGuid
        erpid:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: ErpId
        rmaorderid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '-1'
            column: RmaOrderId
        ordernumber:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: OrderNumber
        dateordered:
            type: datetime
            nullable: true
            column: DateOrdered
        datefirstexpected:
            type: datetime
            nullable: true
            column: DateFirstExpected
        description:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: Description
        projectcode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ProjectCode
        projectname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: ProjectName
        businessunit:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: BusinessUnit
        customernumber:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: CustomerNumber
        customername:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CustomerName
        customeraddressline1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CustomerAddressLine1
        customeraddressline2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CustomerAddressLine2
        customeraddressline3:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CustomerAddressLine3
        customerzipcode:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: CustomerZipCode
        customercity:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CustomerCity
        customerstate:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CustomerState
        customercountrycode:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: CustomerCountryCode
        customercountryname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CustomerCountryName
        customercontact:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: CustomerContact
        customercontactemail:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: CustomerContactEmail
        customerphonenumber:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: CustomerPhoneNumber
        deliverymethod:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: DeliveryMethod
        warehouse:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: Warehouse
        selectioncode:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: SelectionCode
        selectioncodedescription:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: SelectionCodeDescription
        rmaorderlineid:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '-1'
            column: RmaOrderLineId
        linenumber:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '-1'
            column: LineNumber
        itemcode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ItemCode
        defaultvendoritemcode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: DefaultVendorItemCode
        defaultvendorbarcode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: DefaultVendorBarcode
        quantityordered:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            options:
                default: '0'
            column: QuantityOrdered
        quantityreceived:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            options:
                default: '0'
            column: QuantityReceived
        quantitytoreceive:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            options:
                default: '0'
            column: QuantityToReceive
        dateexpected:
            type: datetime
            nullable: true
            column: DateExpected
        lineinstruction:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LineInstruction
        isbatchnumberitem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsBatchNumberItem
        isserialnumberitem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsSerialNumberItem
        itemweight:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            options:
                default: '0'
            column: ItemWeight
        linedescription:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LineDescription
        itemlongdescription:
            type: string
            nullable: true
            length: 2000
            options:
                fixed: false
            column: ItemLongDescription
        itemdescription:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: ItemDescription
        itembrand:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ItemBrand
        itemdefaultlocation:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ItemDefaultLocation
        linecurrencycode:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: LineCurrencyCode
        itemrmaprice:
            type: decimal
            nullable: false
            precision: 19
            scale: 4
            options:
                default: '0'
            column: ItemRmaPrice
        reasoncode:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: ReasonCode
        reasondescription:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ReasonDescription
        salesorderid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SalesOrderId
        salesordernumber:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: SalesOrderNumber
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
