PenD\Docker\Application\Model\Notificationgroups:
    type: entity
    table: NotificationGroups
    id:
        key:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            id: true
            column: Key
            generator:
                strategy: IDENTITY
    fields:
        gotolink:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: GotoLink
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
    lifecycleCallbacks: {  }
