PenD\Docker\Application\Model\Printrules:
    type: entity
    table: PrintRules
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: Description
        issystem:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: IsSystem
        isactive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: IsActive
        printerid:
            type: string
            nullable: false
            length: 260
            options:
                fixed: false
            column: PrinterId
        label:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: Label
        jobtype:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: JobType
        documenttype:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: DocumentType
        copies:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: Copies
        colormode:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: ColorMode
        duplexmode:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: DuplexMode
        pageorientation:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: PageOrientation
        bin:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Bin
        pagesize:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PageSize
        createdon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CreatedOn
        createdby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: CreatedBy
        modifiedon:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ModifiedOn
        modifiedby:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: SYSTEM
            column: ModifiedBy
        rowversion:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: RowVersion
        printscaletype:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PrintScaleType
    lifecycleCallbacks: {  }
